/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreementFooter: typeof import('./../components/login/AgreementFooter.vue')['default']
    AppLogo: typeof import('./../components/common/AppLogo.vue')['default']
    ChatInputBar: typeof import('./../components/im/ChatInputBar.vue')['default']
    ChatMessageBubble: typeof import('./../components/im/ChatMessageBubble.vue')['default']
    ChatSessionItem: typeof import('./../components/im/ChatSessionItem.vue')['default']
    DemoEntryCard: typeof import('./../components/demo/DemoEntryCard.vue')['default']
    HomeBannerSwipe: typeof import('./../components/home/HomeBannerSwipe.vue')['default']
    HomeKingKongGrid: typeof import('./../components/home/HomeKingKongGrid.vue')['default']
    PrivacyAgreementSheet: typeof import('./../components/splash/PrivacyAgreementSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
